### ISSUE TITLE
显示错误: ValueError: 'a' cannot be empty unless no samples are taken

### ISSUE THREAD

**Issue by lishenbin** [cqylunlun/GLASS#5]
Traceback (most recent call last):
  File "/root/GLASS/GLASS-main/main.py", line 351, in <module>
    main()
  File "/root/miniconda3/envs/glass_env/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/glass_env/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/glass_env/lib/python3.9/site-packages/click/core.py", line 1720, in invoke
    return _process_result(rv)
  File "/root/miniconda3/envs/glass_env/lib/python3.9/site-packages/click/core.py", line 1657, in _process_result
    value = ctx.invoke(self._result_callback, value, **ctx.params)
  File "/root/miniconda3/envs/glass_env/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/GLASS/GLASS-main/main.py", line 299, in run
    flag = GLASS.trainer(dataloaders["training"], dataloaders["testing"], dataset_name)
  File "/root/GLASS/GLASS-main/glass.py", line 233, in trainer
    for i, data in enumerate(training_data):
  File "/root/miniconda3/envs/glass_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/glass_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/glass_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/glass_env/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/glass_env/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/glass_env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/glass_env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/GLASS/GLASS-main/datasets/mvtec.py", line 169, in __getitem__
    aug = PIL.Image.open(np.random.choice(self.anomaly_source_paths)).convert("RGB")
  File "numpy/random/mtrand.pyx", line 951, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
请问这个错误该怎么解决

**Comment by cqylunlun** [comment]
参考#2，请下载纹理数据集DTD，并正确配置`--augpath`。

**Comment by lishenbin** [comment]
好的, 十分感谢

**Comment by crazyblueer** [comment]
Hello,
I encountered the same error "a" cannot be empty unless no samples are taken, even though I am pretty sure that I have config my paths for datapath and augpath correctly. Here is my .sh file:
datapath=/c/Users/A/Downloads/GLASS-main/tomatoes
augpath=/c/Users/A/Downloads/GLASS-main/dataset/dtd/images
classes=('red_tomatoes')
flags=($(for class in "${classes[@]}"; do echo '-d '"${class}"; done))

cd ..
python main.py \
    --gpu 0 \
    --seed 0 \
    --test ckpt \
  net \
    -b wideresnet50 \
    -le layer2 \
    -le layer3 \
    --pretrain_embed_dimension 1536 \
    --target_embed_dimension 1536 \
    --patchsize 3 \
    --meta_epochs 640 \
    --eval_epochs 1 \
    --dsc_layers 2 \
    --dsc_hidden 1024 \
    --pre_proj 1 \
    --mining 1 \
    --noise 0.015 \
    --radius 0.75 \
    --p 0.5 \
    --step 20 \
    --limit 392 \
  dataset \
    --distribution 0 \
    --mean 0.5 \
    --std 0.1 \
    --fg 0 \
    --rand_aug 1 \
    --batch_size 8 \
    --resize 288 \
    --imagesize 288 "${flags[@]}" tomatoes $datapath $augpath
